### ISSUE TITLE
.proto 生成的 .go 文件似乎有版本兼容问题, 请问项目正常生成的相关版本是哪些

### ISSUE THREAD

**Issue by hick** [icowan/grpc-world#1]
直接 clone 本项目以后可以直接跑起来, 但是包括 clone 下来先用 git mod download ,  包括 https://juejin.im/post/6844903972818403335 中说明的方式去安装 protoc 和 protoc-gen-go , 生成的 .go 有明显的差异, 导致 make run 的时候跑不起来, 对比是有明显的差异 diff patch 如附件
[service.pb.go.patch.zip](https://github.com/icowan/grpc-world/files/5269352/service.pb.go.patch.zip)

,  跑的时候提示:

`# github.com/icowan/grpc-world/pkg/grpc
pkg\grpc\handler.go:39:67: undefined: pb.ServiceServer`

整个 clone 下来以后的文件也传上来仅供参考,  包括 go.mod 和 go.sum 都有大概看, 没搞大清楚为什么 protoc 命令重新生成以后,  执行的时候会自动更新 go.mod 和 go.sum 

求指点,  谢谢

**Comment by icowan** [comment]
@hick 您好，报这个错是 grpc 版本的问题，可以在go.mod将版本修改一下

```
google.golang.org/grpc v1.30.0
```

**Comment by hick** [comment]
多谢提示,  之前这个 go.mod 也是自动被更新的,     刚手工改了 go.mod 重新 download , go list -m all | grep grpc  确认的版本号, 好像有新问题,   去确认 protoc-gen-go.exe 没变化,  感觉我本地环境各个版本有些乱了, 我回头换个新环境再试试,

**Comment by hick** [comment]
好像也没干什么, 就是过了俩天好像就好了,  俩个机器都是, 谢了
